config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :rooms, only: [:show, :index]
  get "/*page", to: "static_pages#show"
  root "static_pages#show", page: "home"
end

app/models/room.rb
require 'simple_enum/mongoid'

class Room
  include Mongoid::Document
  include Mongoid::Timestamps
  include SimpleEnum::Mongoid

  field :room_number, type: String
  field :area, type: String
  field :address, type: String
  field :direction, type: String
  field :number_of_bedrooms, type: String
  field :number_of_bathrooms, type: String
  field :project, type: String
  field :floor, type: String
  field :utilities, type: String
  field :environment, type: String
  field :description, type: String
  field :price_per_metre_square, type: String
  field :price, type: String
  field :images, type: Array
  field :city, type: String
  field :district, type: String
  field :code, type: String
  field :provider_url, type: String

  as_enum :provider_site, ["muabannhadat.vn", "nhadat24h.net"]

  validates :code, presence: true
end

app/models/settings.rb
class Settings < Settingslogic
  source "#{Rails.root}/config/application.yml"
  namespace Rails.env
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  http_basic_authenticate_with name: ENV["BASIC_AUTHEN_USERNAME"], password: ENV["BASIC_AUTHEN_PASSWORD"]

  protect_from_forgery with: :exception

  include ApplicationHelper
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @search = Room.ransack params[:q]
    selector = RansackMongo::Query.parse(params[:q])
    selector["provider_site_cd"] = selector["provider_site_cd"].to_i if selector.present?
    @rooms = Room.where(selector).order(code: :asc).page(params[:page]).per Settings.rooms.page_size
  end

  def show
    @room = Room.find params[:id]
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def show
    if valid_page?
      render template: "static_pages/#{params[:page]}"
    else
      render_404
    end
  end

  private
  def valid_page?
    File.exist? Pathname.new("#{Rails.root}/app/views/static_pages/#{params[:page]}.html.erb")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title page_title = ""
    base_title = t ".crawler"
    page_title.empty? ? base_title : page_title + " | " + base_title
  end

  def render_404
    render file: "#{Rails.root}/public/404.html", status: 404
  end

  def index_for counter, page, per_page
    (page - 1) * per_page + counter + 1
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <p>© <%= Date.today.year %> <%= t ".rooms_crawler" %></p>
  </small>
  <nav>
    <ul>
      <li><%= link_to t(".about"), Settings.about_page_url %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t(".crawler"), root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t(".rooms"), rooms_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield :title %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/magnific-popup.min.css">
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/jquery.magnific-popup.min.js"></script>
  </head>
  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <div class="container-body">
        <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %>"><%= message %></div>
        <% end %>
        <%= yield %>
        <div class="clearfix"></div>
      </div>
      <%= render "layouts/footer" %>
    </div>
  </body>
</html>

app/views/rooms/_list_photos.html.erb
<div class="col-md-12 text-center"><%= image_tag images[0], class: "cover-image" %></div>
<div class="col-md-12">
  <br>
</div>
<div class="list-photos">
    <%= render partial: "photos", collection: images, as: :photo %>
</div>

app/views/rooms/_photos.html.erb
<% if photo_counter > Settings.rooms.image_number %>
  <%= link_to image_path(photo), class: "hidden" do %>
    <%= image_tag photo, class: "list-photo-item" %>
  <% end %>
<% else %>
  <%= link_to image_path(photo) do %>
    <% if photo_counter == Settings.rooms.image_number %>
      <%= image_tag photo, class: "list-photo-item last-item" %>
      <span class="other-photo"><%= "(+#{@room.images.size - Settings.rooms.image_number})" %></span>
    <% else %>
      <%= image_tag photo, class: "list-photo-item" %>
    <% end %>
  <% end %>
<% end %>

app/views/rooms/_room.html.erb
<tr>
  <td><%= index_for room_counter, @rooms.current_page, Settings.rooms.page_size %></td>
  <td><%= room.provider_site %></td>
  <td><%= link_to room.code, room %></td>
  <td><%= room.city %></td>
  <td><%= room.district %></td>
  <td><%= room.area %></td>
  <td><%= room.price %></td>
</tr>

app/views/rooms/_search.html.erb
<div class="col-md-6 col-md-offset-3">
  <%= search_form_for search do |f| %>
    <p><%= f.select :provider_site_cd_eq,
      options_for_select(Room.provider_sites.hash, params.dig(:q, :provider_site_cd_eq)),
      {include_blank: t(".select_provider")}, {class: "form-control", placeholder: t(".code_place_holder")} %></p>
    <p><%= f.search_field :code_cont, value: params.dig(:q, :code_cont),
      class: "form-control", placeholder: t(".code_place_holder") %>
    </p>
    <p><%= f.search_field :city_or_district_cont, value: params.dig(:q, :city_or_district_cont),
      class: "form-control", placeholder: t(".city_place_holder") %></p>
    <p><%= f.search_field :area_cont, value: params.dig(:q, :area_cont),
      class: "form-control", placeholder: t(".area_place_holder") %></p>
    <p><%= f.search_field :price_cont, value: params.dig(:q, :price_cont),
      class: "form-control", placeholder: t(".price_cont_place_holder") %></p>
    <%= f.submit t(".search"), class: "btn btn-primary pull-right" %>
  <% end %>
</div>

app/views/rooms/index.html.erb
<div class="row">
  <div class="col-md-12">
    <h2 class="text-center"><%= t ".room_list"%></h2>
    <hr>
    <%= render "search", search: @search %>
    <div class="col-md-12"><hr></div>
    <table class="table table-hover table-bordered">
      <thead>
        <tr>
          <th><%= t ".id" %></th>
          <th class="col-md-2"><%= t ".name_site" %></th>
          <th class="col-md-2"><%= t ".code" %></th>
          <th class="col-md-2"><%= t ".city" %></th>
          <th class="col-md-2"><%= t ".district" %></th>
          <th class="col-md-2"><%= t ".area" %></th>
          <th class="col-md-2"><%= t ".price" %></th>
        </tr>
      </thead>
      <tbody>
        <%= render @rooms %>
      </tbody>
    </table>
    <div class ="text-center"><%= paginate @rooms %></div>
    <div class ="text-center"><%= page_entries_info @rooms %></div>
  </div>
</div>

app/views/rooms/show.html.erb
<div class="row">
  <div class="col-md-12">
    <h2 class="text-center"><%= t ".room_detail"%></h2>
    <br>
    <div class="room-photos"><%= render("list_photos", images: @room.images) if @room.images.present? %></div>
    <br>
    <table class="table table-hover table-bordered">
      <tbody>
        <tr>
          <th class="col-md-3"><%= t ".code" %></th>
          <td><%= @room.code %></td>
        </tr>
        <tr>
          <th><%= t ".city" %></th>
          <td><%= @room.city %></td>
        </tr>
        <tr>
          <th><%= t ".district" %></th>
          <td><%= @room.district %></td>
        </tr>
        <tr>
          <th><%= t ".address" %></th>
          <td><%= @room.address %></td>
        </tr>
        <tr>
          <th><%= t ".direction" %></th>
          <td><%= @room.direction %></td>
        </tr>
        <tr>
          <th><%= t ".project" %></th>
          <td><%= @room.project %></td>
        </tr>
        <tr>
          <th><%= t ".room_number" %></th>
          <td><%= @room.room_number %></td>
        </tr>
        <tr>
          <th><%= t ".area" %></th>
          <td><%= @room.area %></td>
        </tr>
        <tr>
          <th><%= t ".floor" %></th>
          <td><%= @room.floor %></td>
        </tr>
        <tr>
          <th><%= t ".number_of_bedrooms" %></th>
          <td><%= @room.number_of_bedrooms %></td>
        </tr>
        <tr>
          <th><%= t ".number_of_bathrooms" %></th>
          <td><%= @room.number_of_bathrooms %></td>
        </tr>
        <tr>
          <th><%= t ".utilities" %></th>
          <td><%= @room.utilities %></td>
        </tr>
        <tr>
          <th><%= t ".environment" %></th>
          <td><%= @room.environment %></td>
        </tr>
        <tr>
          <th><%= t ".description" %></th>
          <td><%= @room.description.html_safe %></td>
        </tr>
        <tr>
          <th><%= t ".price_per_metre_square" %></th>
          <td><%= @room.price_per_metre_square %></td>
        </tr>
        <tr>
          <th><%= t ".price" %></th>
          <td><%= @room.price %></td>
        </tr>
        <tr>
          <th><%= t ".source" %></th>
          <td><%= link_to nil, @room.provider_url %></td>
        </tr>
      <tbody>
    </table>
  </div>
</div>

app/views/static_pages/about.html.erb
<% provide :title, t(".about") %>
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield :title %></title>
  </head>
  <body>
    <h1 class="text-center"><%= t ".about" %></h1>
    <p><%= t ".about_us" %></p>
    <%= t ".group_members" %>
    <li> Do Hong Son - SE03775 </li>
    <li> Nguyen Van Luc - SE03901 </li>
    <li> Nguyen Chi Cuong - SE03825 </li>
  </body>
</html>

app/views/static_pages/home.html.erb
<% provide :title, t(".home") %>
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield :title %></title>
  </head>
  <body>
    <h1 class="text-center"><%= t ".home" %></h1>
    <p class="text-center"><%= t ".welcome" %></p>
  </body>
</html>